# Generated by Django 4.1.12 on 2023-10-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocApi', '0002_alter_customuser_options_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgproject',
            name='userstasks',
            field=models.ManyToManyField(blank=True, related_name='projects', to='DocApi.usertask'),
        ),
    ]
